export const projectsHero = {
  headline: 'Project Directory',
  subtext: 'A transparent ledger of our structural interventions. Filter by region, focus area, or status to review the exact locations and outcomes of our work.',
  backgroundImage: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=2072&auto=format&fit=crop',
};

export const projectDirectory = [
  {
    slug: 'solar-micro-grids-rajasthan',
    title: 'Solar Micro-Grids for Arid Communities',
    location: 'Rajasthan, India',
    year: '2023',
    status: 'Completed',
    beneficiaries: '45 Villages (approx. 12,000 individuals)',
    description: 'Deploying decentralized renewable energy infrastructure to 45 off-grid villages, powering essential services and local enterprises while drastically reducing reliance on diesel generators.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=2072&auto=format&fit=crop',
  },
  {
    slug: 'mangrove-restoration-kerala',
    title: 'Mangrove Restoration Initiative',
    location: 'Kerala, India',
    year: 'Ongoing',
    status: 'Active',
    beneficiaries: 'Coastal Communities (approx. 8,500 individuals)',
    description: 'Rehabilitating vital coastal buffers to protect against storm surges and restore marine biodiversity. A critical step in long-term ecosystem resilience.',
    image: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=2041&auto=format&fit=crop',
  },
  {
    slug: 'agritech-cooperative-gujarat',
    title: 'Women\'s Agritech Cooperative',
    location: 'Gujarat, India',
    year: '2022',
    status: 'Scaled',
    beneficiaries: '250 Female Farmers',
    description: 'Equipping female farmers with modern tools and direct market access to ensure food security, increase margins, and foster financial independence.',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    slug: 'education-infrastructure-bihar',
    title: 'Digital Learning Centers',
    location: 'Bihar, India',
    year: '2024',
    status: 'Active',
    beneficiaries: '5,000 Students',
    description: 'Building modern, solar-powered learning centers equipped with high-speed internet to bridge the digital divide in rural education districts.',
    image: 'https://images.unsplash.com/photo-1524069290683-0457abfe42c3?q=80&w=2070&auto=format&fit=crop',
  },
  {
    slug: 'clean-water-rajasthan',
    title: 'Deep-Well Water Infrastructure',
    location: 'Rajasthan, India',
    year: '2021',
    status: 'Completed',
    beneficiaries: '15 Villages',
    description: 'Drilling deep wells and establishing community-managed water distribution networks to eliminate water scarcity during dry seasons.',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?q=80&w=2072&auto=format&fit=crop',
  },
  {
    slug: 'soil-health-punjab',
    title: 'Regenerative Soil Intervention',
    location: 'Punjab, India',
    year: '2023',
    status: 'Active',
    beneficiaries: '1,200 Farmers',
    description: 'Transitioning farmers from chemical-heavy conventional farming to organic, regenerative practices that restore the long-term health of the soil.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop',
  },
];
